name: cupertino_country_picker
description: "A beautifully designed iOS-style country picker for Flutter apps. Easily integrate a Cupertino-style country selector with search functionality, flags, dial codes, and a smooth user experience. Perfect for login screens, phone number inputs, and region-based features."

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supercharged: ^2.1.1
  simple_animations: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/flags/

  fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600

license: MIT